pkp/pkp-lib#5540 component for date and time format form
pkp/ui-library pull request #113
Opened 2020-08-05 12:43 UTC by Vitaliy-1

PHP-side of the form implementation in this PR: https://github.com/pkp/pkp-lib/pull/6144

2020-08-06 09:39 UTC, NateWr commented on src/components/Form/context/DateTimeForm.vue
> +			const time = this.fields.find(element => element.name === 'timeFormat');
Let's change `element` to `field` in each case just to be more descriptive.

2020-08-06 09:42 UTC, NateWr commented on src/components/Form/context/DateTimeForm.vue
> +			const timeOptions = time.options[localeKey].find(element => element.value === time.value[localeKey]);
And `element` to `option` here to be more descriptive.

2020-08-06 09:43 UTC, NateWr commented on src/components/Form/context/DateTimeForm.vue
> +			const timeOptions = time.options[localeKey].find(element => element.value === time.value[localeKey]);
Also, I _think_ these variable names (`shortDateOptions`, `longDateOptions`, `timeOptions`) should be singular (`shortDateOption`, etc). Is that right?

2020-08-06 09:45 UTC, NateWr commented on src/components/Form/context/DateTimeForm.vue
> +		 *
Add a description for the docblock.

2020-08-06 09:45 UTC, NateWr commented on src/components/Form/context/DateTimeForm.vue
> +			if (!['dateFormatShort', 'dateFormatLong', 'timeFormat'].find(element => element === name)) {
`element` to `fieldName` here.

2020-08-18 17:25 UTC, Vitaliy-1 commented
@NateWr, it's ready for the second round of review, I've added moment.js for date & time formatting and localization

2020-08-19 09:38 UTC, NateWr requested changes
:+1:

2020-08-19 09:38 UTC, NateWr commented on src/components/Form/context/DateTimeForm.vue
> +	data: function() {
This is not important, but just a heads-up that we can also use a shortened syntax:

```
data() {
  ...
}
```

The same is true for each of the functions below. You do not need to make this change if you don't want, just mentioning it.

2020-08-19 09:38 UTC, NateWr commented on src/components/Form/context/DateTimeForm.vue
> +		 * @param longDateTime object  new label and value for the short date and time field
In JavaScript we use a different docblock format for defining variables. So these should look like:

```
@param {Array} newfields
```

If you're using a syntax highlighter with your IDE that recognises .vue files it should give you some appropriate coloring when defined that way.

2020-08-19 09:38 UTC, NateWr commented on src/components/Form/context/DateTimeForm.vue
> +import moment from 'moment';
Let's add moment.js to our package.json files so that we ensure we have the dependency. It will need to be added to the package.json in ui-library and ojs/omp/ops. Add it to the `dependencies` object and use "^2.27.0".

2020-08-26 11:18 UTC, NateWr commented
Replaced by https://github.com/pkp/ui-library/pull/117

2020-08-26 11:18 UTC, closed without merging