Handle smarty variables in Tinymce
pkp/ui-library pull request #123
Opened 2020-11-15 13:22 UTC by withanage

@NateWr 

I have added the  logic to handle smarty variables into tinymce using a callback function.

This jsfiddle shows the functionality for it. 
https://fiddle.tiny.cloud/xyhaab

Issue [#122](https://github.com/pkp/orcidProfile/issues/122)

In SiteHandler.js there is also a place, where tinymce is used, let me know, if that is also used  and has to be added too.

A small demo of the added functionality.
![tinymce](https://user-images.githubusercontent.com/1921992/99186026-c8d06e00-274d-11eb-97c6-8732340a8dcb.gif)

2020-11-16 11:03 UTC, NateWr requested changes
Looks good! Go ahead and port it to `master` as well.

2020-11-16 11:03 UTC, NateWr commented on src/components/Form/fields/FieldRichTextarea.vue
> +				},
Use the new ES6 syntax for consistency:

```
urlconverter_callback(url) {
```

And the use `const` instead of `var` for these.

Also, there's an extra space between `return` and `url` on line 187.

2020-11-17 12:05 UTC, xmlFlow commented on src/components/Form/fields/FieldRichTextarea.vue
> +				},
@NateWr 
Thanks for the Tipp with the ui-library linter. 
I have added the changes now.

2020-11-17 12:05 UTC, withanage commented on src/components/Form/fields/FieldRichTextarea.vue
> +				},
@NateWr
Thanks for the Tipp with the ui-library linter.
I have added the changes now.

2020-11-17 15:21 UTC, merged