[UI-LIBRARY] #6850 Author Grid + API Calls
pkp/ui-library pull request #170
Opened 2021-11-14 15:30 UTC by defstat

2021-11-16 11:51 UTC, NateWr requested changes
Still a few things to address here.

2021-11-16 11:51 UTC, NateWr commented on src/components/Container/WorkflowPage.vue
> +			this.workingPublication.authors = [...contributors];
In a comment on the last PR, https://github.com/pkp/ui-library/pull/167#discussion_r726988041, I suggested emitting contributor changes all with one event. The same is true for publications. So, right now, you've got a bunch of different events emitted from the contributors list panel:

```
@edited="contributorEdited"
@added="contributorAdded"
@deleted="contributorDeleted"
@primary-contact-changed="primaryContactChanged"
@contributors-order-changed="contributorsOrderChanged"
@preview-publication-authors="previewPublicationAuthors"
@reset-contributors="resetContributors"
```

When designing components, you should try to decouple the individual actions of the component from the interactions with parent components. So although there may be several places in `ContributorsListPanel` where an event is fired, it only needs to fire a couple of events:

```
addContributor(...) {
  // ajax request, etc. ...
  this.$emit('updated:contributors', newContributors);
},
deleteContributor(...) {
   // ajax request, etc. ...
   const newContributors = contributors.filter(...);
   this.$emit('updated:contributors', newContributors);
}
```

Done this way, the parent component should only need to listen to a couple of events:

```
@updated:publication="setWorkingPublication"
@updated:contributors="setContributors"
```

And then you only need a couple of methods to handle all changes.

```
methods: {
  setWorkingPublication(publication) {
     // ...
  },
  setContributors(contributors) {
     // ...
  }
}
```

2021-11-16 11:51 UTC, NateWr commented on src/components/ListPanel/contributors/ContributorsListPanel.vue
> +			this.$emit('reset-contributors', this.itemsBeforeReordering);
Do you need to emit this event? Isn't `cancelOrdering` the same as `toggleOrdering` when it is toggled off? Above, with `toggleOrdering`, the old items are simply restored and there's no need to emit an event to sync the order with `WorkflowPage`

2021-11-16 11:51 UTC, NateWr commented on src/components/ListPanel/contributors/ContributorsListPanel.vue
> +			}
There's a comment on the old PR that suggests you removed this `if` class (lines 318-329), but it's still here. https://github.com/pkp/ui-library/pull/167#discussion_r728847878

2021-11-16 11:51 UTC, NateWr commented on src/components/ListPanel/contributors/ContributorsListPanel.vue
> +							);
There's a comment in the old PR that the fetch mixin, and the `self.setItems` method, is not needed here: https://github.com/pkp/ui-library/pull/167#discussion_r727004964

You can replace the `self.setItems()` call with:

```js
self.items = self.items.filter(i => i.id !== id);
```

Then remove the `import fetch from ...` statement at the top.

2021-11-16 11:51 UTC, NateWr commented on src/components/ListPanel/contributors/ContributorsListPanel.vue
> +				}
Are you maybe missing a `success()` handler here that will emit the new contributors array so that `WorkflowPage` can update?

2021-11-29 17:13 UTC, defstat commented on src/components/Container/WorkflowPage.vue
> +			this.workingPublication.authors = [...contributors];
Fixed

2021-11-29 17:24 UTC, defstat commented on src/components/ListPanel/contributors/ContributorsListPanel.vue
> +							);
Done

2021-11-29 17:30 UTC, defstat commented on src/components/ListPanel/contributors/ContributorsListPanel.vue
> +			this.$emit('reset-contributors', this.itemsBeforeReordering);
Removed the `this.$emit('reset-contributors', this.itemsBeforeReordering);` and changed it with `this.items = this.itemsBeforeReordering`

2021-11-29 17:36 UTC, defstat commented on src/components/ListPanel/contributors/ContributorsListPanel.vue
> +				}
Done

2021-11-29 17:37 UTC, defstat commented on src/components/ListPanel/contributors/ContributorsListPanel.vue
> +			}
Removed

2021-11-30 11:05 UTC, NateWr commented on src/components/ListPanel/contributors/ContributorsListPanel.vue
> +			this.$emit('reset-contributors', this.itemsBeforeReordering);
I think you're going to get a warning message in the console that you shouldn't change a prop. So I think you do need to emit an event here, but you don't need to emit a special event. You can emit the same `updated:contributors` event as below.

2021-12-15 12:38 UTC, NateWr requested changes

2021-12-15 17:50 UTC, defstat commented on src/components/ListPanel/contributors/ContributorsListPanel.vue
> +							:disabled="isLoading"
Added to `data`

2021-12-15 17:53 UTC, defstat commented on src/components/ListPanel/contributors/ContributorsListPanel.vue
> +						</pkp-button>
added the `:disabled="isLoading"` to both buttons

2021-12-15 17:55 UTC, defstat commented on src/components/ListPanel/contributors/ContributorsListPanel.vue
> +						</pkp-button>
added the :disabled="isLoading" to 4 buttons

2021-12-15 17:58 UTC, defstat commented on src/components/ListPanel/contributors/ContributorsListPanel.vue
> +		openPreviewModal() {
Added

2021-12-15 18:01 UTC, defstat commented on src/docs/components/WorkflowPage/previews/PreviewWorkflowPage.vue
> +								:items-max="workingPublication.authors.length"
Removed

2021-12-15 18:03 UTC, defstat commented on src/docs/components/WorkflowPage/previews/PreviewWorkflowPage.vue
> +				contributors: {
Not sure if I fixed it

2021-12-16 15:26 UTC, defstat commented on src/components/ListPanel/contributors/ContributorsListPanel.vue
> +		},
Fixed for Firefox - the focus goes to order button. 
When in chrome the focus goes to the edit button right next to the clicked button (with or without the additional code)

2021-12-16 15:32 UTC, defstat commented on src/docs/components/WorkflowPage/previews/PreviewWorkflowPage.vue
> +					],
Fixed

2021-12-16 15:34 UTC, defstat commented on src/docs/components/WorkflowPage/previews/PreviewWorkflowPage.vue
> +									{value: 'AX', label: 'Åland Islands'}
Done

2021-12-16 15:40 UTC, defstat commented on src/docs/data/publication.js
> +			preferredPublicName: {en_US: 'Δημητριος Ευσταθιου'},
Removed the author with the greek name

2021-12-16 15:42 UTC, defstat commented on src/components/Container/WorkflowPageOJS.vue
> +			this.activeForm = activeForm;
Removed

2021-12-19 16:00 UTC, defstat commented on src/docs/components/WorkflowPage/previews/PreviewWorkflowPage.vue
> +				},
Some of the items in `ui-library/src/docs/components/Forms/helpers` do not have the same let's say name attribute as the fields in the current form. What should I do with them? (for example the `biography` field)

2021-12-20 14:08 UTC, merged

2022-01-10 14:03 UTC, NateWr commented on src/docs/components/WorkflowPage/previews/PreviewWorkflowPage.vue
> +				},
Don't worry about it. The preview is just for dev/testing/documentation. The data doesn't need to be an exact replica of the application -- just a demonstration of the functionality.