pkp/pkp-lib#7318 stats issues page
pkp/ui-library pull request #217
Opened 2022-10-11 18:24 UTC by bozana

s. https://github.com/pkp/pkp-lib/issues/7318
This is the vue page for the Statistics > Issues page

2022-10-12 12:57 UTC, NateWr requested changes

2022-10-12 12:57 UTC, NateWr commented on src/components/Container/StatsIssuesPage.vue
> +	extends: StatsPage,
I think we should extend `StatsPublicationsPage` and just override the things that are different. Otherwise there is a lot of duplicated code between this and the publications page component.

2022-10-24 14:55 UTC, NateWr commented on src/components/Container/StatsIssuesPage.vue
> +	}
Rather than duplicating the full `downloadReport()` method, which includes the ajax call and other things, just split out the bit of code that you need to modify into its own method. I _think_ that's just the download file name, so in `StatsPublicationsPage` you can do:

```js
let downloadFileName = this.getReportFilenameParts()
	.filter(i => i)
	.join('_') + '.csv';
```

Then you only have to override `getReportFilenameParts()` in the stats page. (you'll probably do something similiar with the context stats page).

2022-10-26 08:35 UTC, NateWr commented on src/components/Container/StatsPublicationsPage.vue
> +					.replace('to', '_'),
It just occurred to me that this probably won't work here or in `StatsIssuesPage.vue`. The `to` is part of a string that will be translated so won't appear in most languages.

2022-10-26 10:27 UTC, bozana commented on src/components/Container/StatsPublicationsPage.vue
> +					.replace('to', '_'),
Oh, yes :-DDD Good catch!!!
I will then change that...
Also, I am wondering if having issue identifications in the file name could lead to the long and thus unreadable file names -- e.g. if the journal uses/has only issue title...
Thus, what do you think about having the file name that only contains e.g. stats_submissions_currentDateTime, and adding the parameters in the CSV file in the same way we list them on the download modal, e.g.:

```
"Date Range","All dates"
Sections,AllSections
Issues,AllIssues
"Search Phrase",anti

ID,Title,Total,"Abstract Views","File Views",PDF,HTML,Other
17,"The Antimicrobial, heavy metal resistance and plasmid profile of coliforms isolated from nosocomial infections in a hospital in Isfahan, Iran",14,14,0,0,0,0
```

2022-10-26 16:02 UTC, bozana commented on src/components/Container/StatsPublicationsPage.vue
> +					.replace('to', '_'),
Only timeline report considers only either views or downloads, the other report consider both. Thus I will then add timeline type and timeline interval to that report. The others will have only date range, filters (if exist) and search phrase.

2022-10-27 11:08 UTC, merged