Bugfix/main/8442 fix date filter
pkp/ui-library pull request #232
Opened 2022-11-22 16:38 UTC by jonasraoni

2022-11-23 10:37 UTC, NateWr requested changes
Nice use of promises. I hope to refactor away from `$.ajax()` to `fetch()` soon. Just a couple of small comments.

2022-11-23 10:37 UTC, NateWr commented on src/components/Container/StatsEditorialPage.vue
> +				this.response = response;
Rather than sticking this into the component `data`, can we use a scoped variable so it doesn't effect anything outside of this function?

```js
let response;
let NetworkError = function(r) {
	response = r;
}
```

That way it won't clutter up the component data.

2022-11-23 10:37 UTC, NateWr commented on src/components/DateRange/DateRange.vue
> +		},
It looks like `invalidEndDateMaxLabel` may not be used?

2022-11-26 10:01 UTC, jonasraoni commented on src/components/DateRange/DateRange.vue
> +		},
Ah, this is already on the `main` branch:
https://github.com/pkp/ui-library/blob/a47e575b21e53913c1ef1cf07e0445c9c5668a2d/src/components/DateRange/DateRange.vue#L263

An error is generated when the code reaches that point, after the fix it will work fine.

2022-11-26 10:06 UTC, jonasraoni commented on src/components/Container/StatsEditorialPage.vue
> +				this.response = response;
Given the function isn't an arrow function, `this` will be "self-contained", as I'm instantiating it with `new NetworkError` later in the code.
p.s.: The errored response isn't used, but I didn't want to lose information :)

2022-12-01 15:50 UTC, merged