Added 'Same institution as author' badge to reviewer select modal
pkp/ui-library pull request #275
Opened 2023-07-05 07:53 UTC by MrRob100

![Screenshot 2023-07-05 at 08 45 54](https://github.com/pkp/ui-library/assets/43947674/3bd59f86-00a5-467e-b316-afab919ee102)

Adding 'Same institution as author' badge to the list of potential reviewers during reviewer selection

This is the Vue part of the feature here https://github.com/pkp/pkp-lib/pull/9090

2023-07-31 12:29 UTC, jardakotesovec requested changes

2023-07-31 12:29 UTC, jardakotesovec commented on src/components/Container/AdvancedSearchReviewerContainer.vue
> +				<button
This is really minor suggestion. In Vue.js usually more complex expressions are usually done via computed properties. And in template you would refer computed property.

2023-07-31 12:29 UTC, jardakotesovec commented on src/components/Container/AdvancedSearchReviewerContainer.vue
> +				<div
From accessibility point of view its lot better to express lists semantically via ul&li tags, so its well interpreted by screen readers.

2023-07-31 12:29 UTC, jardakotesovec commented on src/components/Container/AdvancedSearchReviewerContainer.vue
> +				>
I have not tested the code so I might be wrong - but this looks like it will always render all authors regardless whether show more is clicked?

2023-08-01 11:26 UTC, MrRob100 commented
@jardakotesovec These are in now

2023-09-06 08:02 UTC, jardakotesovec commented
@Devika008 @Vitaliy-1 @asmecher 

Hi! Currently testing how it behaves in OMP. And it does show list of authors in both modals, when adding reviewer for both Internal and External reviews. Is that desirable?

<img width="848" alt="Screenshot 2023-09-06 at 9 55 53" src="https://github.com/pkp/ui-library/assets/1590681/33be2852-742f-4060-9f6e-287266ead00a">


Also for some reason the detection whether reviewer is from same university as one of the authors is not working on OMP.. will check why is that.

2023-09-08 02:45 UTC, merged