Change submission language
pkp/ui-library pull request #280
Opened 2023-08-22 08:05 UTC by jyhein

- Change the submission language after submission
- Show the language of the submission in the workflow page and the author dashboard
- In the modal window editors can change the language and add/edit required metadata
- The submission's metadata can be edited even if the submission's locale is not one of the currently supported submission locales
- The language of the submission can not be changed if the status of the publication is published or there are more than one version

2024-06-10 14:04 UTC, bozana commented
Hi @jardakotesovec, could you please take a look at this PR?
Thanks a lot!

2024-06-17 10:42 UTC, jardakotesovec requested changes
Hi Jyrki,
you are on the good track - but hopefully we will be able to simplify things.

I added some suggestions how to proceed - feel free to follow up with questions either on github or mattermost.

2024-06-17 10:42 UTC, jardakotesovec commented on src/components/Container/ChangeSubmissionLanguage.vue
> +import {inject, reactive} from 'vue';
We intend to follow vue.js recommendations by default (unless we have some good reason to do otherwise). In this case we use the <script setup> syntax which is recommended when using SFC - https://vuejs.org/guide/scaling-up/sfc.html .

What that means in practice is really couple of adjustments, like using defineProps, which has the same syntax for props, but its using this macro - https://vuejs.org/guide/components/props.html


Good template to follow is `pages/reviewerSubmission/ReviewerSubmissionPage*` files, which has very similar situation of creating modal.

So please also move the business logic to the separate store component - which is really just moving it, as the store follow the component lifecycle and use exact same composition api. But it makes easier from plugin to interact with it rather than when its directly in component - more details is here - https://main--6555d3db80418bb1681b8b17.chromatic.com/?path=/docs/guide-pinia-store--docs .
-

But its mostly about just moving things around as the core idea of using composition api is the same.

And once the whole UI would be simplified (less api interactions and workflow interactions) - it also will be lot easier to add it to storybook.

2024-06-17 10:42 UTC, jardakotesovec commented on src/components/Container/ChangeSubmissionLanguage.vue
> +		contributors: {
Number of props after the adjustments should hopefully drop significantly.

There is good benefit to have the modals as independent as possible from main screen and keep the communication between them at the minimum - as that makes easier for both to evolve independently.

If we manage to move the updating meta to the API endpoint, instead of handling the whole process from the UI - I think we will get just to passing the cslmform and submission. It could be even more independent and just pass submissionId & cslmform and fetch the submission from the API.

2024-06-17 10:42 UTC, jardakotesovec commented on src/components/Container/ChangeSubmissionLanguage.vue
> +	setup(props, {emit}) {
I think it has such a large impact on underlying workflow page and its going to be used quite rarely - I would recommend just to reload the page once the form is succesfully submitted to reload the workflow page, rather than trying to update everything. That should simplify things significantly - and thats always good thing :-).

2024-06-17 10:42 UTC, jardakotesovec commented on src/components/Container/ChangeSubmissionLanguage.vue
> +					url: url,
With new composition API I created couple of composables to make various things easier.  Please follow the useFetch examples here - https://main--6555d3db80418bb1681b8b17.chromatic.com/?path=/docs/composables-usefetch--docs

It will handle many things for you, things like passing csrf token and adding the x-http-method-override logic and error handling for unexpected errors.

2024-06-17 10:42 UTC, jardakotesovec commented on src/components/Container/ChangeSubmissionLanguage.vue
> +					props.contributors,
Created another composable for creating api urls, so we don't have to constantly passing them from PHP as configuration - check out - https://main--6555d3db80418bb1681b8b17.chromatic.com/?path=/docs/composables-useapiurl--docs

2024-06-17 10:42 UTC, jardakotesovec commented on src/components/Container/ChangeSubmissionLanguage.vue
> +				const form = cloneDeep(state.form);
The form thats being presented in mockups is not multilingual. I would suggest disable multilingual option there, so you don't have to fight it, because currently it still indicates the globe and you are using css override to hide the switcher. Overriding css should be the last resort..  as thats always asking for troubles down the road. If we start evolving Form component - it just stops working and it will be difficult to notice that.

2024-06-17 12:09 UTC, jardakotesovec commented
One more thing - we also now have useForm composable - but its not covered in storybook yet, because its still in early stages, but could be useful for your use case.

Purpose is basically to stop writing code which is traversing the form structures - and have that abstracted that out.

So for example if you would want to programtically set some values, you can do something like:

```
const { form, set, setValue } = useForm(props.changeLanguageForm);

setValue('abstract', abstract);
```

And you can use the `set` to process the changes coming from form:

```
<pkp-form
  v-bind="form"
  @set="set"
/>

```

As mentioned its early implementation - so if you run into any issues there please let me know and I will improve it..

2024-06-24 08:23 UTC, jyhein commented on src/components/Container/ChangeSubmissionLanguage.vue
> +				const form = cloneDeep(state.form);
How do you suggest to disable multilingual option? The form is multilingual and needs to be sent as such. Adding hide-option prop to Form.vue for the switcher is simple but it will leave those globes visible.

2024-06-24 08:26 UTC, jyhein commented on src/components/Container/ChangeSubmissionLanguage.vue
> +	setup(props, {emit}) {
So, store component js does the language change but ChangeSubmissionLanguage.vue reloads the page?

2024-06-24 14:00 UTC, jardakotesovec commented on src/components/Container/ChangeSubmissionLanguage.vue
> +				const form = cloneDeep(state.form);
Are you creating new dedicated API endpoint to trigger the language change?  Such endpoint would probably expect just simple fields based on the modals - target language, title, abstract, ... .  And I would not expect this to be sent in multi lingual data shape.  Does that sound reasonable or you had some other plan?

2024-06-24 14:00 UTC, jardakotesovec commented on src/components/Container/ChangeSubmissionLanguage.vue
> +	setup(props, {emit}) {
Store basically can have all the business logic, including the reload.

2024-06-25 11:08 UTC, bozana commented on src/components/Container/ChangeSubmissionLanguage.vue
> +				const form = cloneDeep(state.form);
Hi @jyhein, yes, we have discussed this internally and we have decided to have a new API endpoint for this, so that all business logic can be removed from Vue.
@ewhanson, I suppose the API endpoint will go into the PKPSubmissionController? What should be the API path for this, e.g. submissions/$submissionId/publications/$publicationId/changeLocale, or submissions/$submissionId/changeLocale or .../setLocale... or .../locale... or ... ? :-)
Thanks!

2024-07-04 18:28 UTC, ewhanson commented on src/components/Container/ChangeSubmissionLanguage.vue
> +				const form = cloneDeep(state.form);
Yes, I would add it to `PKPSubmissionController` and would put this under `submissions/{$submissionId}/saveLocale`. You can look at the `saveContributorsOrder` endpoint as a good example to follow: https://github.com/pkp/pkp-lib/blob/c3c4090d90c88fc5ce3a9877d7b0fa6d61c18300/api/v1/submissions/PKPSubmissionController.php#L260-L262. 

Another thing that will need to be considered is which roles will be allowed to make this change.

Happy to have a look at it once it's ready for review!

2024-07-15 16:16 UTC, bozana commented on src/components/Container/ChangeSubmissionLanguage.vue
> +				const form = cloneDeep(state.form);
I think journal manager and editor can make the change -- they always have access to submisison functions, but for section editor (sub editors) we need to check if the user is assigned to the submission.

2024-08-06 12:35 UTC, jardakotesovec commented
@jyhein I see there is some good progress - let me know when its ready for review. Thank you.

2024-08-07 17:17 UTC, ewhanson commented on src/components/Container/WorkflowPageOMP.vue
> +			this.workingPublication.authors.forEach(
No problem with this, but just wondering if this was something that had been breaking the change submission locale functionality in some way?

2024-08-07 17:19 UTC, ewhanson commented on src/pages/workflow/changeSubmissionLanguageStore.js
> +			apiUrl: {value: apiUrl},
I would specify which API URL this is since it's used both as the publication endpoint and as part of the `changeLocale` endpoint. Maybe something like `publicationApiUrl` as distinct from `changeLocaleApiUrl`?

2024-08-07 17:20 UTC, ewhanson commented on src/pages/workflow/changeSubmissionLanguageStore.js
> +			props.form.fields[2].value[props.form.primaryLocale];
Is the publication title guaranteed to be index 2 in the `props.form.fields` array? This may be totally fine but just wanted to flag it.

2024-08-07 17:21 UTC, ewhanson commented on src/pages/workflow/changeSubmissionLanguageStore.js
> +		(async () => {
This looks fine, but just wanted to double check (cc: @jardakotesovec) that an IIFE was beset practice for preloading this data here as I'm less familiar with working with stores.

2024-08-07 17:23 UTC, ewhanson commented on src/pages/workflow/changeSubmissionLanguageStore.js
> +				form.fields.forEach((f) => {
Another minor one, but for readability, I prefer having more explicit variable names as they make it easier to parse the code at a glance (maybe `field` instead of `f`?).

2024-08-07 17:24 UTC, ewhanson commented on src/pages/workflow/changeSubmissionLanguageStore.js
> +			location.reload();
Probably another question for @jardakotesovec on house style. Elsewhere in the codebase, the `window` is explicitly referenced (so `window.location.reload()` instead of just `location.reload()`). Should we keep it consistent with the rest of the codebase and include `window` or is it better to leave it off?

2024-08-14 06:24 UTC, jardakotesovec commented on src/components/Container/WorkflowPageOMP.vue
> +			this.workingPublication.authors.forEach(
Hi @jyhein, Could you provide some details on this one? Also not sure why this was needed and whether its related to locale functionality.

2024-08-14 06:27 UTC, jardakotesovec commented on src/pages/workflow/ChangeSubmissionLanguage.vue
> +					<PkpForm
Interesting, have not seen use of aria-live user on form like this. Can you help me understand how it improves accessibility?

2024-08-14 06:31 UTC, jardakotesovec commented on src/pages/workflow/changeSubmissionLanguageStore.js
> +			apiUrl: {value: apiUrl},
Rather than destructing 'value'.  More common approach with composition api, is to keep it as ref and when you need to access value, you do it like: `form.value.action = apiUrl.value + '/changeLocale'` and as Erik mentioned destructing it like {apiUrl: publicationApiUrl} would make it bit more friendly.

2024-08-14 07:09 UTC, jardakotesovec commented on src/pages/workflow/changeSubmissionLanguageStore.js
> +		(async () => {
@ewhanson @jyhein Its bit unusual, not technically wrong though :-). Did you have any reason to wrap it in function like this? Maybe just to avoid variable name conflicts? That could be avoided for example with `const {data: publication, fetch: fetchPublication} = useFetch(..).`

Or if you would want to keep it in function, I would suggest just to create function with name and than invoke it.

2024-08-14 07:12 UTC, jardakotesovec commented on src/pages/workflow/changeSubmissionLanguageStore.js
> +			Object.keys(data).forEach((key) => (form[key] = data[key]));
My understanding here is that you want to extend `set` function, so if the language gets changed it also updates title and abstract, right?

To just to make it bit more explicit that you are extending default function. You can get the `set` function from userForm - const {set} = useForm(...).   And than create your own function `setCustom`, which calls the original set function and do your custom bit.

2024-08-14 07:17 UTC, jardakotesovec commented on src/pages/workflow/changeSubmissionLanguageStore.js
> +			// Set fields when changing language
Here I think you could use `getValue('locale')` from `const {getValue} = useForm(...).` Because at this moment form structure will be already updated from the `set` call.

2024-08-14 07:19 UTC, jardakotesovec commented on src/pages/workflow/changeSubmissionLanguageStore.js
> +			location.reload();
This is very minor thing, but yes we can keep it consistent with rest of the code base and add window

2024-08-14 07:31 UTC, jardakotesovec commented on src/pages/workflow/changeSubmissionLanguageStore.js
> +		}
This would be nice to also cover with some helper function from useForm, but we don't have it yet..  Its fine to leave it as it is.

2024-08-14 07:46 UTC, jardakotesovec commented on src/pages/workflow/changeSubmissionLanguageStore.js
> +							getLocaleName(newLocale),
Yes, locale keys are being determined in build time, therefore it can't really understand variables.

But in this case you are always updating title and abstract, so instead of loop, you can just always apply it for title and abstract.

Or if you want to stick with the loop, you can define the locale keys for example like this:
```
const DescriptionLocaleKeys = {
title: tk`submission.list.changeSubmissionLanguage.metadataDescription.title`,
abstract: tk`submission.list.changeSubmissionLanguage.metadataDescription.abstract`
}

```

Which than can be used as `t(DescriptionLocaleKeys['title'], {language: ...})`

Let me know if there is any issue with this.

2024-08-14 07:58 UTC, jardakotesovec commented
@jyhein Hi Jyrki, I am done with code review, apologies for delay. Its looking good. Its all really just minor suggestions.

2024-08-15 09:29 UTC, jyhein commented on src/pages/workflow/changeSubmissionLanguageStore.js
> +							getLocaleName(newLocale),
My idea  here was to keep the code as general as possible, in case there will be additional fields

2024-08-15 09:36 UTC, jyhein commented on src/components/Container/WorkflowPageOMP.vue
> +			this.workingPublication.authors.forEach(
I got an error that the value is expected to be boolean but that was when vue side updated contributor props. Not sure if if it is needed anymore (or at all)

2024-08-15 09:41 UTC, jyhein commented on src/pages/workflow/changeSubmissionLanguageStore.js
> +		(async () => {
Vue complained something about making <script setup> async (.vue file), so I had to wrap it in a function

2024-09-13 09:10 UTC, jardakotesovec commented on src/components/Container/WorkflowPageOMP.vue
> +			this.workingPublication.authors.forEach(
@jyhein Oki, can you please double check whether is needed?

2024-09-13 10:10 UTC, jyhein commented on src/pages/workflow/changeSubmissionLanguageStore.js
> +			apiUrl: {value: apiUrl},
I wanted to make apiUrl (publicationApiUrl) immutable. No other reason

2024-09-16 10:23 UTC, jyhein commented on src/components/Container/WorkflowPageOMP.vue
> +			this.workingPublication.authors.forEach(
I removed the code because I didn't see any errors OMP side when changing language. I didn't test any further

2024-09-24 19:05 UTC, jardakotesovec commented on src/pages/workflow/changeSubmissionLanguageStore.js
> +							getLocaleName(newLocale),
Thats good intention for sure, I have only mixed feeling always when I see some string replacement as that feels fragile. I know its very likely to be fine, but theoretically there can be some scenario where the locale name could be substring of some word in the description in some specific language. Its unlikely, but that still would make me to prefer to use the locale keys as suggested above.

2024-09-25 07:56 UTC, jyhein commented on src/pages/workflow/changeSubmissionLanguageStore.js
> +							getLocaleName(newLocale),
Ok

2024-09-25 13:09 UTC, merged