[UI-LIBRARY][main] #7505 Initial Commit Upload - Delete - Download JATS File
pkp/ui-library pull request #300
Opened 2023-11-24 10:47 UTC by defstat

2023-11-24 17:54 UTC, asmecher requested changes
I'll send this along to someone else for a proper review when we're ready, but in the meantime, just a quick comment!

2023-11-24 17:54 UTC, asmecher commented on src/components/ListPanel/jats/SubmissionJatsListPanel.vue
> +								<span>Last Modification at </span>
Hard-coded English text needs localization.

2023-11-24 19:47 UTC, defstat commented on src/components/ListPanel/jats/SubmissionJatsListPanel.vue
> +								<span>Last Modification at </span>
Fixed

2023-12-05 22:30 UTC, asmecher commented
@jardakotesovec, would you mind taking a look at this PR (part of https://github.com/pkp/pkp-lib/issues/7505)? Thanks!

2023-12-05 22:30 UTC, asmecher commented
@defstat, I think you were going to raise something specific here about error handling?

2023-12-06 19:44 UTC, defstat commented
@jardakotesovec I was having some trouble figuring out how I should handle possible errors. Is there a "standard" way of doing that when using PKP's vue.js components? Are we handling exceptions in a particular way?

2023-12-07 09:00 UTC, jardakotesovec commented on src/components/ListPanel/jats/SubmissionJatsListPanel.vue
> +			type: String,
No need to be passing translation as props. Just use  this.t('translation.key'), and vite plugin will detect it and automatically include to available translations. This is quite recent work - https://github.com/pkp/pkp-lib/issues/9371

2023-12-07 11:47 UTC, jardakotesovec commented on src/components/ListPanel/jats/SubmissionJatsListPanel.vue
>  					'{$modificationDate}',
You should be able to pass the arguments directly to the `t` function.

this.t('publication.jats.lastModified', {modificationDate: this.workingJatsProps.updatedAt })

2023-12-07 16:15 UTC, defstat commented on src/components/ListPanel/jats/SubmissionJatsListPanel.vue
> +	}
It does exist though [here](https://github.com/defstat/ui-library/blob/i7505/src/components/ListPanel/jats/SubmissionJatsListPanel.vue#L5).

Are you perhaps referring to something else?

2023-12-07 16:25 UTC, defstat commented on src/components/ListPanel/jats/SubmissionJatsListPanel.vue
>  					'{$modificationDate}',
Sure - removed the calculated value and added the `t` function to the `span` directly like such 
```
<span>{{ t('publication.jats.lastModified', {modificationDate: this.workingJatsProps.updatedAt, username: this.workingJatsProps.uploaderUserName}) }}</span>
```

2023-12-07 16:34 UTC, defstat commented on src/components/ListPanel/jats/SubmissionJatsListPanel.vue
>  				@updated:files="setJatsFile"
Changed it to `:upload-progress-label="t('submission.upload.percentComplete')"`

2023-12-07 17:42 UTC, defstat commented on src/components/ListPanel/jats/SubmissionJatsListPanel.vue
> +		<slot>
Thanks @jardakotesovec, yes, placing and being able to use the component was the problem for me, so I left it in the list panels. You are right, never the less, that should not be there. So I made the following changes:

1. Moved the old `JatsListPanel` to the where you recommended, namely `pages/workflow/PublicationSectionJats.vue`
2. Referenced this component into the `WorkflowPage.vue`, instead of the `import JatsListPanel from '@/components/ListPanel/jats/SubmissionJatsListPanel.vue';`
3. Moved the `PKP/classes/components/listPanels/JatsListPanel.php` to `PKP/classes/components/PublicationSectionJats.php`
4. Removed the references to `ListPanel` from `PKP/classes/components/PublicationSectionJats.php` making the appropriate changes to make that work.
5. In `PKP/js/load.js` I referenced the `import PublicationSectionJats from '@/pages/workflow/PublicationSectionJats.vue';`
6. In `PKP/js/load.js` I registered the new component as such `VueRegistry.registerComponent('PkpPublicationJats', PublicationSectionJats);`
7. In `APP/templates/workflow/workflow.tpl` I changed the appropriate tab's tag from `<jats-list-panel>` to `<pkp-publication-jats>`

With those steps we have the new component free of dependences from `ListPanel` which can be placed (I think) independently where ever we need to, keeping the same functionality as before.

Please check if that meets our goals.

2023-12-12 13:04 UTC, jardakotesovec commented on src/components/Container/WorkflowPage.vue
>  import Composer from '@/components/Composer/Composer.vue';
Please keep naming consistent and import it as PublicationSectionJats

2023-12-12 13:11 UTC, jardakotesovec commented on src/components/ListPanel/jats/SubmissionJatsListPanel.vue
> +		<slot>
@defstat That looks great, only thing that I added as commint to pkp-lib is to not include it to lib/pkp/js/load.js as its not general component, its fine just to imported in workflow.vue in 'components'.

2023-12-18 18:04 UTC, defstat commented on src/components/Container/WorkflowPage.vue
>  import Composer from '@/components/Composer/Composer.vue';
Fixed

2023-12-18 21:12 UTC, merged