pkp/pkp-lib#9773 html text enhancement for rich field text
pkp/ui-library pull request #335
Opened 2024-03-06 12:58 UTC by touhidurabir

for pkp/pkp-lib#9773

2024-03-09 00:11 UTC, asmecher commented on src/components/Form/fields/FieldRichText.vue
> +						// we need to have better control as tinymec is converting specials chars to html entities
*tinymce

2024-03-09 00:20 UTC, asmecher commented on src/components/Form/fields/FieldRichText.vue
> +					// Note that not all options available to 5.0+ that being used right now
This function doesn't appear to correctly handle entities. Try for example:
- Open the `Title & Abstract` metadata form
- Edit the `Abstract` field and manually type `&amp;` into it somewhere
- Copy that section of text and paste it into the `Title` field

You'll see that the `&amp;` is unexpectedly decoded into a `&` in the title.

Likewise, try typing a raw `&` into the abstract field and copy/pasting that into the title; you'll see that the operation fails entirely.

I'm not actually sure we need to use `paste_preprocess` at all; I'm not able to replicate the behaviour described here with the XSS attack (`<img src="onerror=alert(1)">`) described below without it.

2024-03-09 00:21 UTC, asmecher requested changes
Thanks, @touhidurabir, I've added a couple notes.

2024-03-09 08:11 UTC, touhidurabir commented on src/components/Form/fields/FieldRichText.vue
> +					// Note that not all options available to 5.0+ that being used right now
@asmecher I think that is the expected behaviour I am trying to set there . you see, tinymce convert any paste data into entity converting format for example , `<img src="onerror=alert(1)">` turned into `&lt;img src=&quot;onerror=alert(1)&quot;&gt;` it's then not possible to properly only extract the context from within encapsulated in tags . Also `&amp;` on paste turning into `&` still stored in DB as `&amp;` otherwise it will be double decoded as `&amp;amp;` . also copy pasting `&` does remain as `&` . see the attached screenshot as below 
<img width="1027" alt="CleanShot 2024-03-09 at 14 00 28@2x" src="https://github.com/pkp/ui-library/assets/2587979/e2e34e97-a9f6-4e6e-ba1a-e9afd2329fd7">

it stored the data in DB as `BOLD2 BOLD.  &amp; some text &amp;` when copy pasting form abstract field to title field and saving without modification . 

The point is getting only the context, removing any tags/formatting/encoding  as tinymce itself enforce encoding . I think this bring better result. sorry if I am missing something here .

2024-06-07 13:49 UTC, touhidurabir commented on src/components/Form/fields/FieldRichText.vue
> +					// Note that not all options available to 5.0+ that being used right now
@asmecher the main purpose of the `paste_preprocess` was to extract only the content without any tags or styles and let user apply their own style as we only allow just 5 html tags such as `b,i,u,sup,sub` . The rest of quirks are gone as I have removed the server side extra sanitization and set the `valid_elements` prop on tinymce editor . So we can remove if we don't want apply the content extraction only anymore . 

As we have discussed last time, I am removing it .

2024-06-07 21:48 UTC, merged