Log reviewer response
pkp/ui-library pull request #350
Opened 2024-05-20 13:49 UTC by MrRob100

<img width="1022" alt="Screenshot 2024-05-20 at 10 44 42" src="https://github.com/pkp/ui-library/assets/43947674/03b39554-e29e-4f12-9e3f-42d953671dac">

2024-05-22 08:31 UTC, jardakotesovec commented on src/pages/workflow/WorkflowLogResponseForModal.vue
> +					<div class="form-flex h-full">
Could se use the PkpForm here? And create the form configuration on php side as we have the classes to do that there?

I know its bit of the hassle for such simple form - but its important to stay consistent on having configuration driven forms as that let us to evolve them over time.

2024-05-22 08:34 UTC, jardakotesovec commented on src/pages/workflow/WorkflowLogResponseForModal.vue
> +								<div>
Was not ButtonRow working for this case?

Generally what we aim in styling is to use either tailwindcss for simple cases and when its more comples&repeating pattern we would create component - example would be SideModalLayout2Columns.

Would like to avoid using some global css classes that has been created in past - that makes very difficult to keep oriented whats used where and makes impossible to make changes. Thats also for example why we introduced vairants in Button.vue and other components rather than overriding their styling from outside - because than it makes impossible to change these components over time.

2024-05-22 08:39 UTC, jardakotesovec commented on src/pages/workflow/WorkflowLogResponseForModal.vue
> +				url: props.url,
With composition API I created couple of composable helpers to handle common actions for API interactions, modals and localisation.

Please check them out in [storybook](https://main--6555d3db80418bb1681b8b17.chromatic.com/?path=/docs/composables-usefetch--docs), in particular useModal, useFetch, useLocalise and useUrl are most common one.  We also have useForm when we need to explicitely set/get some values from the form, not sure if you would need that - thats has not been documented yet. If you think it would be useful for you let me know I will prioritize to documenting the use cases.

I will merge this improvement for useFetch soon, which I believe would be relevant for you - https://github.com/pkp/pkp-lib/issues/9977

2024-05-22 08:46 UTC, jardakotesovec commented
@MrRob100 After code improvements I will also ask you to add it to storybook, so we have that modal snapshoted, which helps with awarness that such modal do exist and it also helps with preventing some regressions over time as its screenshots are always compared to baseline.

It will require following
- create stories file, which need to have button which opens this modal via play function. That what ensures that opened modal is screenshoted
- create mdx file with simple description, so it does appear in storybook - and it automatically is able to pick up the props and show them there


One of the best examples is ReviewerSubmissionPage.stories, as that also have modals that are being opened via play function:
```
export const OpenModalAccepted = {
	play: async ({canvasElement}) => {
		// Assigns canvas to the component root element
		const canvas = within(canvasElement);
		const user = userEvent.setup();

		await user.click(canvas.getByText('Read Round 1 Review'));
	},
	decorators: [
		() => ({
                        // this needs to be adjusted based on your specific modal to ensure the whole modal gets screenshoted
			template: '<div style="height: 1600px"><story/></div>',
		}),
	],
};

```

Happy to give more guidance on mattermost for storybook if needed, there is just couple of things to watch out so the modal gets properly screenshoted.

2024-05-22 13:28 UTC, jardakotesovec commented on src/pages/workflow/WorkflowLogResponseForModal.vue
> +	}
One thing I forgot to mention. Could we also move the business logic to the WorkflowLogResponseForModalStore.js ?

Good (similar) example to this would be in roundHistoryModalStore.js which is also handling logic for modal.

Some resources why we do this and some guidance
- https://main--6555d3db80418bb1681b8b17.chromatic.com/?path=/docs/guide-technical-roadmap--docs#pinia-stores-35
- https://main--6555d3db80418bb1681b8b17.chromatic.com/?path=/docs/guide-pinia-store--docs

Good is that the syntax is completely the same as in component when using composition api. So its just matter of moving things over.

2024-05-30 02:15 UTC, MrRob100 commented
I have redone this using the pkp-form component. In order to make the form footer sit on the bottom of the modal, I have had to add some styling to the Form component. I have checked and it doesn’t seem to have knock-on effects on the other forms. Also, there doesn’t seem to be support for a cancel button in the pkp-form component which is why I have left that out. I can alter it to allow for one if we like. Thoughts @jardakotesovec @Devika008

2024-06-04 13:25 UTC, jardakotesovec requested changes
Here is example for storybook - https://github.com/pkp/ui-library/commit/815ea2a764bfb4eeee16217c0c36dd70346f249d

This ensures that if you open that story it opens the modal - and as result it gets automatically screenshotted in CI to ensure it looks good over time.

You can see it in storybook (cd lib/ui-library && npm run storybook).

Please just refine it a bit with some description. Otherwise I think one simple story suffice.

2024-08-15 08:45 UTC, jardakotesovec commented on src/components/Form/Form.vue
>  	position: relative;
I think I commented on this one before. Are we sure this does not break forms with multiple groups? Like creating spaces between individual groups as well.

2024-08-15 08:46 UTC, jardakotesovec commented
@MrRob100 Thanks! Looking good, just need to do some testing. Would you be able to rebase it, so its up to date with main branches? Having difficulties to run it. There has been lots of merged lots of changes recently.

2024-09-04 12:13 UTC, MrRob100 commented on src/components/Form/Form.vue
>  	position: relative;
@jardakotesovec I have checked and it seems to display as normal for example in the form here management/settings/context#contact.

2024-09-10 15:53 UTC, jardakotesovec requested changes
Thanks for the storybook addition. Just couple small tweaks! And also make sure it does not include changes outside of this work. Thank you!

2024-09-10 15:53 UTC, jardakotesovec commented on src/components/Form/Form.vue
>  	position: relative;
@MrRob100 Right, but thats because these are long forms which take full page height. But if there would be short form (like yours) with multiple groups, it would equally space between individual groups.

Can you try to add margin-top: auto  to the pkpFormPage__footer - that should position button down, and not affect the group. 

Thanks!

2024-09-10 15:53 UTC, jardakotesovec commented on src/components/ListPanel/doi/DoiItemVersionModal.vue
> -				<PkpTable :labelled-by="versionHeaderId">
These changes probably should not be here?

2024-09-10 15:53 UTC, jardakotesovec commented on src/pages/workflow/WorkflowLogResponseForModal.stories.js
> +import WorkflowLogResponseForModal from './WorkflowLogResponseForModal.vue';
Thank you for adding this to storybook - thats great.. it help us to be aware of this screen and because it makes screenshots it also helps to make sure it still looks correct as we change things.

2024-09-10 15:53 UTC, jardakotesovec commented on src/pages/workflow/WorkflowLogResponseForModal.vue
> +				class="h-full"
Here we just need to npm run lint in ui-library folder (after npm install). This should happen automatically if you have dependencies installed there I think. 

It will fix the naming convention to <PkpForm>

2024-09-10 15:53 UTC, jardakotesovec commented on src/pages/workflow/WorkflowLogResponseForModal.vue
> +	logResponseForm: {type: Object, required: true},
are the legacyOptions needed actually

2024-09-10 15:53 UTC, jardakotesovec commented on src/pages/workflow/workflowLogResponseForModalStore.js
> +		}
Its not well documented as its still in early stages, but for these cases we now have useForm composable.

```
import useForm from '@/composables/useForm'
const {set: updateForm, form} = useForm(props.logResponseForm);
```

Which provides the set function, so you don't need the updateForm function.

2024-09-10 19:25 UTC, MrRob100 commented on src/components/Form/Form.vue
>  	position: relative;
@jardakotesovec I was unable to resolve this by styling the pkpFormPage__footer. I have pushed another solution that just targets the pkpFormPage__footer that is used in the vue modal

2024-09-11 19:38 UTC, MrRob100 commented on src/components/Form/Form.vue
>  	position: relative;
@jardakotesovec Removed those css changes completely now

2024-11-11 08:56 UTC, jardakotesovec commented on src/managers/ReviewerManager/useReviewerManagerActions.js
> +		});
To update data, it should be enough just to call finishedCallback, so the main store triggers data reload.

Something like this should work
```
openSideModal(WorkflowLogResponseModal, {
  title: title,
  submissionId: submissionId,
  logResponseForm: dashboardStore.componentForms.logResponseForm,
}, {onClose: finishedCallback});
```

2024-11-11 08:57 UTC, jardakotesovec requested changes
Looking great! I think just make sure that the data update works after suggested change and should be ready for merging (at least the ui-part).

2024-11-19 11:20 UTC, merged