pkp/pkp-lib#8248 COUNTER R5 TSV reports
pkp/ui-library pull request #373
Opened 2024-07-01 10:00 UTC by bozana

s. https://github.com/pkp/pkp-lib/issues/9666

2024-07-10 12:38 UTC, jardakotesovec commented on src/components/Form/counter/CounterReportForm.vue
> +	components: {
Goal here will be to stop extending and overriding form methods. Form component should provide good enough API via props and emits to achieve these custom submits and I suspect it already can. And if not we can improve it.

I see in the code that Form already has option to only emit success action, when the action === 'emit', thats what might be good enough to handle the submitting outside of the form?

Additionally we have now composables/useForm, which unfortunately is not documented yet as its still evolving quite a bit, but its purpose is to make easier to programatically change or retrieve form state.

As very basic use can be just for maintaining form state - since we don't inherit from Page.vue, which has the `set` method, you should be able to do something like

const {form, set} = useForm(props.statsForm)

and use the `form` and `set` on the <PkpForm> component.

Please check it out - and feel free to follow-up so we can improve things.

2024-07-10 12:40 UTC, jardakotesovec commented on src/components/ListPanel/counter/CounterReportsListPanel.vue
> +				<pkp-header>
We don't have mature enough replacement for ListPanel, so nothing to change on that front.

Only things that would make sense to leverage apart from compositionAPI would be to useUrl and useFetch for the api communication. These composables will abstract many things for you, like handling headers, csrf token or displaying error if backend fails.

 You should be able to find good examples both in storybook and in existing code.

2024-08-27 09:51 UTC, bozana commented
Hi @jardakotesovec, I believe this is ready for your next review :-)
I think I have considered all suggestions from the first review round.
I have integrated your changes for the customSubmit to work, and slightly adapted it in the commit [adapt form](https://github.com/pkp/ui-library/pull/373/commits/3dbf5d24c918ff8378509e5b34a312a6f52595fa).
And finally, why are the tests failing i.e. how should I proceed regarding them?
Thanks a lot!

2024-08-29 14:11 UTC, jardakotesovec requested changes
Nothing major really..  but suggested couple of improvements.

Really appreciate willingness to familiarise with the composition api even its not completely necessary for this particular task. There is some getting used to - but it really gives lots of power for more complex UIs.

2024-08-29 14:11 UTC, jardakotesovec commented on src/components/ListPanel/counter/CounterReportsListPanel.vue
> +}
Generally trying to minimise cases where we override component styles from outside, as it makes difficult to evolve the component on its own when consumer are relying on such implementation details.

But in this case you can easily adjust the styling like this:
```
					<span :id="item.Report_ID" class="text-lg-normal">
						{{ item.Report_Name }} ({{ item.Report_ID }})
					</span>
```

2024-08-29 14:11 UTC, jardakotesovec commented on src/components/ListPanel/counter/CounterReportsListPanel.vue
> +			type: String,
We don't need these anymore in 3.5.  Just use 

this.t in options api
or in composition api - import {useLocalize} from '@/composables/useLocalize' and const {t} = useLocalize()

And it will automatically get that translation down to the client without explicitly passing that from backend.

2024-08-29 14:11 UTC, jardakotesovec commented on src/components/ListPanel/counter/CounterReportsListPanel.vue
> +			type: String,
I don't think this is needed anymore.. but does not hurt..

2024-08-29 14:11 UTC, jardakotesovec commented on src/components/ListPanel/counter/CounterReportsListPanel.vue
> +			if (!report) {
Can this actually happen?

2024-08-29 14:11 UTC, jardakotesovec commented on src/pages/counter/CounterReportsPage.vue
> +	counterReportsListPanel: {type: Array, required: true},
Is it really Array? I would expect this to be Object?

2024-08-30 07:51 UTC, bozana commented on src/components/ListPanel/counter/CounterReportsEditModal.vue
> +			pkp.eventBus.$emit(
The error comes from the API itself that also checks a few things. The form is COUNTER specific -- it is a JSON, for example:
`{"Code":1030,"Severity":"Fatal","Message":"Insufficient Information to Process Request","Data":"Missing customer_id."}`.
An example where it happened: https://github.com/pkp/pkp-lib/issues/10350 -- I was treating the UI form inputs wrongly, so API error occurred.

2024-10-08 08:43 UTC, bozana commented on src/components/ListPanel/counter/CounterReportsListPanel.vue
> +			type: String,
I will then leave it for now...

2024-10-08 08:49 UTC, bozana commented on src/components/ListPanel/counter/CounterReportsListPanel.vue
> +			if (!report) {
Theoretically it cannot happen :-)
Would it be possible that someone manipulates the list panel and edit function?
However, I will remove it :-)

2024-10-08 12:24 UTC, bozana commented on src/components/ListPanel/counter/CounterReportsEditModal.vue
> +<template>
Hi @jardakotesovec, I am not sure I understand this correctly.
We now have the page src/pages/counter/CounterReportsPage.vue. 
Should this file src/components/ListPanel/counter/CounterReportsEditModal.vue be copied to src/pages/counter/CounterReportsEditModal.vue?
:thinking:

2024-10-08 12:32 UTC, bozana commented
Hi @jardakotesovec, I believe I have considered all your comments -- only one question is left -- so it is ready for the next review round :-)
Thanks a lot!

2024-10-09 10:59 UTC, bozana commented on src/components/ListPanel/counter/CounterReportsEditModal.vue
> +<template>
Aaaa... OK, will do... :-)

2024-10-14 10:37 UTC, jardakotesovec reviewed
Just couple small suggestions, nothing major.

2024-10-14 12:21 UTC, bozana commented on src/pages/counter/components/CounterReportsListPanel.vue
> +	}
But I could restructure it all a little bit so that the function getItems is not there...

2024-10-14 12:21 UTC, bozana commented on src/pages/counter/CounterReportsPage.vue
> +		class="pkpNotification--backendPage__header"
I hope I understood this correctly :-)

2024-10-14 12:38 UTC, bozana commented
Hi @jardakotesovec, I think I considered everything, could you please take another look?
Thanks a lot!

2024-10-14 12:59 UTC, jardakotesovec commented on src/pages/counter/components/CounterReportsListPanel.vue
> +});
Just FYI, you don't need to trigger fetch inside onMounted. The whole setup function gets called when the component is about to be created (before onMounted). So I usually call fetch directly inside the setup function:
```
const {
	data,
	fetch,
	isLoading: isLoadingItems,
} = useFetch(apiUrl, {
	method: 'GET',
});

fetch()
```

But it does not make  real difference.

2024-10-14 12:59 UTC, jardakotesovec approved these changes
Thank you for going along with composition api and other new things!

2024-10-14 13:29 UTC, bozana commented on src/pages/counter/components/CounterReportsListPanel.vue
> +});
I have changed it... Thanks!

2024-10-14 14:22 UTC, jardakotesovec requested changes

2024-10-15 11:10 UTC, merged