[TEST ONLY]Invitation landing page
pkp/ui-library pull request #382
Opened 2024-07-15 14:24 UTC by ipula

2024-07-18 10:23 UTC, jardakotesovec commented on src/pages/invitation/InvitationPage.vue
> +<template>
Was bit confused by the name of the PR - this is not really invitation landing page.  Its the new component that will be added to the User&Role page, right?

For that best fit is to implement it as self-contained component. I decided to create 'managers' folder for these, as I am also creating similar components to for example manage files. Which has lots of similarities to what you are creating.

Good thing is that these managers have very much the same structure as page. So they have main component and store. And additionally helper components as needed and also additional composables as needed so the store does not become too bloated. Main store should really just provide good quick overview how it all works together.

So I would recommend to transform this to such manager. You can check out that managers/FileManager for inspiration.

I will add some additional comments about things that could be improved along the way.

<img width="931" alt="Screenshot 2024-07-18 at 12 20 54" src="https://github.com/user-attachments/assets/bd766dfe-484e-4753-9e5f-4d6bc0f91e68">

2024-07-18 10:24 UTC, jardakotesovec commented on src/pages/invitation/InvitationPage.vue
> +	>
Lets avoid usin the leading classes, as the line height is already defined as part of the text-3xl-normal class.

2024-07-18 10:25 UTC, jardakotesovec commented on src/pages/invitation/InvitationPage.vue
> +								localize(row.payload.familyName)
For more complex logic is nicer to create dedicated Cell component that includes that logic in form of computed for example, rather all of that within template

2024-07-18 10:26 UTC, jardakotesovec commented on src/pages/invitation/InvitationPage.vue
> +						:key="i"
this is also good candidate for seperate cell component. Also the whole payload should be already parsed. Not sure why the roles should be send as string? In other words JSON.parse should not be necessary here.

2024-07-18 10:28 UTC, jardakotesovec commented on src/pages/invitation/InvitationPage.vue
> +							<li class="border-b border-solid border-[#ddd]">
We already discussed this one - this would be handled by the DropdownActions component

2024-07-18 10:29 UTC, jardakotesovec commented on src/pages/invitation/InvitationPageStore.js
> +
This is good idea, but we don't really have well established pattern for this. Will get to it sometime later on, so feel free to remove it. It will be probably more integrated to the fetching functions, will see.

2024-07-18 10:30 UTC, jardakotesovec commented on src/pages/invitation/InvitationPageStore.js
> +			query: {page: currentPage},
useFetchPaginated should be better fit to calculate paginations - could we use that instead? Just for consistency so the pagination API interactions would be always handled by useFetchPaginated.

2024-09-19 13:29 UTC, withanage requested changes
@ipula  I  have reviewed some of the general coding things.

2024-09-19 13:29 UTC, withanage commented on src/managers/InvitationManager/InvitationManagerStore.js
> +		 */
/**
		 * create user full name
		 * @param String givenName
		 * @param String familyName
		 * @returns String
		 */

I think this  has to be get User full name

FYI @ipula

2024-09-19 13:29 UTC, withanage commented on src/managers/InvitationManager/InvitationManagerStore.js
> +		function getAllInvitedRoles(userGroups) {
FYI @ipula 

add a comment to this function
may be "get all invited roles"

2024-09-19 13:29 UTC, withanage commented on src/managers/InvitationManager/InvitationManagerStore.js
> +			// invitation table data
remove this comment
FYI @ipula

2024-09-19 13:29 UTC, withanage commented on src/managers/InvitationManager/mocks/invitationMock.js
> +			sendEmailAddress: 'ipula7@mailinator.com',
i would use a comon name like journalmanager@mailinator.com

FYI @ipula

2024-09-19 13:29 UTC, withanage commented on src/pages/acceptInvitation/AcceptInvitationPageStore.js
> +				// check user already exists or new user , for the new user set initial username and password for the validations
@ipula  i would remove this comment

2024-09-19 13:29 UTC, withanage commented on src/pages/acceptInvitation/AcceptInvitationUserRoles.vue
> +							? 'Appear on the masthead'
@ipula  can we make this come from a tempalte variable ?

2024-09-19 13:29 UTC, withanage commented on src/pages/userInvitation/UserInvitationPageStore.js
> +		 */
@ipula i think this comment should be deleted,

2024-09-19 13:29 UTC, withanage commented on src/pages/userInvitation/UserInvitationPageStore.js
>  			//page values
@ipula  remove comment

2024-09-19 13:29 UTC, withanage commented on src/pages/userInvitation/UserInvitationUserGroupsTable.vue
> +			<TableRow v-for="(row, index) in allUserGroupsToaAdd" :key="index">
@ipula  here is a typo.

 allUserGroupsToaAdd

after To  'a'

2024-09-19 13:29 UTC, withanage commented on src/pages/userInvitation/UserInvitationUserGroupsTable.vue
>  function addUserGroup() {
@ipula  commented neede.

2024-09-19 13:29 UTC, withanage commented on src/pages/userInvitation/UserInvitationUserGroupsTable.vue
>  function updateUserGroup(index, fieldName, newValue) {
@ipula  comment needed.

2024-09-19 13:29 UTC, withanage commented on src/pages/userInvitation/UserInvitationUserGroupsTable.vue
>  	const userGroupsUpdate = [...store.invitationPayload.userGroupsToAdd];
@ipula  comment needed.

2024-09-19 13:29 UTC, withanage commented on src/pages/userInvitation/UserInvitationUserGroupsTable.vue
>  function removeUserGroup(userGroup, index) {
@ipula  comment needed.

2024-09-19 13:29 UTC, withanage commented on src/pages/userInvitation/UserInvitationUserGroupsTable.vue
> +function modifyUserGroup(index) {
@ipula  comment needed.

2024-09-19 13:32 UTC, ipula commented on public/globals.js
> +		'invitation.cancelInvite.actionName':'Cancel Invite',
In the mockups its says cancel invitation

2024-09-19 13:33 UTC, ipula commented on src/managers/InvitationManager/InvitationManagerStore.js
> +		 */
I will check this with @defstat

2024-09-19 13:34 UTC, withanage commented
@ipula  may be try to fix the tests also here.

2024-09-19 13:36 UTC, withanage commented on public/globals.js
> +		'invitation.cancelInvite.actionName':'Cancel Invite',
ok, then i would change

` 'invitation.cancelInvite.actionName':'Cancel Invite',` this to  ` 'invitation.cancelInvite.actionName':'Cancel Invitation'

2024-09-25 16:58 UTC, jardakotesovec requested changes
Hi Ipula,
I did review of InvitationManager. The others are still for me to pick up next days.

Thanks!

2024-09-25 16:58 UTC, jardakotesovec commented on src/managers/InvitationManager/InvitationManager.vue
> +			<TableColumn></TableColumn>
For this one, lets use t('common.moreActions') with sr-only

2024-09-25 16:58 UTC, jardakotesovec commented on src/managers/InvitationManager/InvitationManager.vue
> +			<PkpButton @click="store.sendInvitation">
Very minor comment, but extra effort with naming makes the code easier to understand.

Here I would suggest createNewInvitation for example.

2024-09-25 16:58 UTC, jardakotesovec commented on src/managers/InvitationManager/InvitationManager.vue
> +					}}
I think you are aware of this one - to move the combining the name to server side as there is more complex logic to that.

2024-09-25 16:58 UTC, jardakotesovec commented on src/managers/InvitationManager/InvitationManager.vue
> +						<br />
Even though I don't have good argument from top of my head for not using <br /> - have not see that for long time for controlling layouts :-).

Could we go with something bit more common. For example wrapping it in div with 'flex flex-col' classes I think should work.

2024-09-25 16:58 UTC, jardakotesovec commented on src/managers/InvitationManager/InvitationManager.vue
> +				</TableCell>
Formatting dates is still on my list to improve for 3.5. For now please use the formatShortDate from '@/composables/useDate', which currently has very basic logic.. but its at least consistent and will improve that in future.

2024-09-25 16:58 UTC, jardakotesovec commented on src/managers/InvitationManager/InvitationManager.vue
> +					/>
Please improve the naming here.  Something like handleInvitationAction for example would be more suitable.

2024-09-25 16:58 UTC, jardakotesovec commented on src/managers/InvitationManager/InvitationManager.vue
> +						label="Invitation management options"
This needs to be localised

2024-09-25 16:58 UTC, jardakotesovec commented on src/managers/InvitationManager/InvitationManagerStore.js
> +		});
I think you don't need create getInvitationApiUrl computed property.  

You can just
```
const {apiUrl: invitationApiUrl} = useApiUrl('invitations');
```

And than pass the invitationApiUrl to the useFetch

2024-09-25 16:58 UTC, jardakotesovec commented on src/managers/InvitationManager/InvitationManagerStore.js
> +			});
Recently I noticed that we also have `common.commaListSeparator` in translations for `, ` :-). So trying to use that.

So instead of ', ' you can use t('common.commaListSeparator')

2024-09-25 16:58 UTC, jardakotesovec commented on src/managers/InvitationManager/InvitationManagerStore.js
> +						'invited ' + new Date(data.createdAt).toLocaleDateString('en-US'),
Same thing, please use the formatShortDate

2024-09-25 16:58 UTC, jardakotesovec commented on src/managers/InvitationManager/InvitationManagerStore.js
> +					givenName: data.givenName,
We are trying to keep the html mark up to absolute minimum in the translations. There is option in dialog to render the body via dedicated component if we need to display something more complex in the message than just text. Its exactly for these cases to avoid this inline html

Please checkout example in https://main--6555d3db80418bb1681b8b17.chromatic.com/?path=/story/components-dialog--with-body-component

2024-09-25 16:58 UTC, jardakotesovec commented on src/managers/InvitationManager/InvitationManagerStore.js
> +		} = useFetchPaginated(getInvitationApiUrl, {
Minor thing - but would be inclined to for example have fetchInvitations - so its clear its fetching the list, not individual invitation.

2024-09-25 16:58 UTC, jardakotesovec commented on src/managers/InvitationManager/InvitationManagerStore.js
> +							await cancelInvitation();
Looking good! I still don't have strong opinion on when/where to use the loading and would like to make it more automatic.  But it does not hurt to keep it here until I have better plan :-).

2024-09-25 16:58 UTC, jardakotesovec commented on src/managers/InvitationManager/InvitationManager.vue
> +	<PkpTable aria-label="Example for basic table">
This aria-label is not ideal :-).

To make the headings/descriptions/buttons bit more consistent across these different tables, we introduced couple of slots where you can put thing without styling it should look fine - example https://github.com/pkp/ui-library/blob/main/src/managers/GalleyManager/GalleyManager.vue#L3

And that will also do correct accessibility automatically, which is connecting the title an description with the table.


It will look bit different compared to figma, but not worry about that. If we need this alternative styling we would add it to the table.

2024-09-25 17:00 UTC, jardakotesovec commented on src/managers/InvitationManager/InvitationManager.mdx
> +
Bit more docs would be nice here.. :-)

Lets please rename this component to UserInvitationManager, as Alec was concerned that this suggests it would handle all invitations. But for example the invitations for reviewers will be likely handled elsewhere.

2024-09-25 17:37 UTC, ipula commented on src/managers/InvitationManager/InvitationManager.vue
> +					}}
yes we have created a issue for that. I'm waiting for Dimithri's input here

2024-09-25 18:18 UTC, ipula commented on src/managers/InvitationManager/InvitationManagerStore.js
> +		});
I don't have an idea why I did this

2024-09-25 18:42 UTC, asmecher commented on src/managers/InvitationManager/InvitationManager.vue
> +					}}
(link: https://github.com/craft-oa/gdpr-invitation/issues/17)

2024-09-26 10:08 UTC, ipula commented on public/globals.js
> +		'invitation.cancelInvite.actionName':'Cancel Invite',
![image](https://github.com/user-attachments/assets/20f43c83-fa4f-4ea2-8d34-9160b154b15f)

2024-10-03 08:08 UTC, jardakotesovec commented on src/pages/userInvitation/UserInvitationPageStore.js
> +		const updatedPayload = ref({});
Please add couple comments, so its clear whats the difference between invitationPayload and updatedPayload.

2024-10-03 08:10 UTC, jardakotesovec commented on src/pages/userInvitation/UserInvitationPageStore.js
> +		function updateWithSelectedUserGroups(userGroups) {
I see that you do some updates directly in UserInvitationUserGroupsTable and some in store.

Original idea, was to keep the store somewhat general - so it should not know too much specifics about the payloads. So if possible to do the userGroup manipulations in UserInvitationUserGroupsTable?

2024-10-03 09:10 UTC, withanage commented on src/managers/UserInvitationManager/UserInvitationManagerStore.js
> +		const currentPage = ref(1);
@jardakotesovec , I discussed this with @Devika008  and she suggested 5 would be better.

2024-10-03 11:56 UTC, jardakotesovec commented on src/pages/acceptInvitation/AcceptInvitationUserAccountDetails.vue
>  		</div>
Below I see multiple FieldText - would be possible to have these configured through the form as usual, rather than just individual Fields here?

2024-10-03 13:37 UTC, jardakotesovec commented on src/pages/userInvitation/UserInvitationUserGroupsTable.vue
> +const props = defineProps({
Can't comment directly there because its not part of this PR.

But can Add Role button should not be part of the table.

You can use bottom-controls slot on the table to add it instead.

2024-10-22 12:15 UTC, jardakotesovec commented on src/managers/UserInvitationManager/UserInvitationManagerCancelInvitationDialogBody.vue
> +
Please use useLocalize instead, useTranslation is deprecated. It works the same, so just fix the import.

2024-10-22 12:17 UTC, jardakotesovec commented on src/managers/UserInvitationManager/UserInvitationManagerStore.js
> +		const {formatShortDate} = useDate();
useLocalize provides 't' as well..  I need to delete useTranslation after making sure its all moved to useLocalize. Thanks!

2024-10-22 12:50 UTC, jardakotesovec commented on src/pages/userInvitation/UserInvitationSearchFormStep.vue
>  	validateFields: {
Does not seems to be used?

2024-10-22 13:03 UTC, ipula commented on src/pages/userInvitation/UserInvitationSearchFormStep.vue
>  	validateFields: {
it used to the messages

2024-10-22 13:05 UTC, jardakotesovec commented on src/pages/userInvitation/UserInvitationSearchFormStep.vue
> +				user = userData.value.items.find(
As mentioned on mattermost - all email/orcid and username are unique - so we have treat them the same when checking whether the result is unique.

2024-10-22 13:06 UTC, jardakotesovec commented on src/pages/userInvitation/UserInvitationSearchFormStep.vue
> +				store.updatePayload('inviteeEmail', user.email);
Please improve the structure - so the logic for updatePayload when user is found is not repeated.

2024-10-22 13:10 UTC, jardakotesovec commented on src/pages/userInvitation/UserInvitationDetailsFormStep.vue
> +				:value="store.invitationPayload.inviteeEmail"
Don't have currently better idea other than using FormDisplay..  I think its actually not that bad :-).  Lets just fix the spacing between each of them. You can set probably something like this on the div: `flex flex-col gap-y-10`

2024-10-22 13:16 UTC, jardakotesovec commented on src/pages/userInvitation/UserInvitationPageStore.js
> +			}
Can you help me understand why when its initial value it should not be included in updatedPayload.  This is probably correct..  but not intuitive.. so some additional comment would be useful.

2024-10-22 13:18 UTC, ipula commented on src/pages/userInvitation/UserInvitationPageStore.js
> +			}
if user did not update those values It will used in request payload. We only use user updated values on for the api request

2024-10-22 13:19 UTC, jardakotesovec commented on src/pages/userInvitation/UserInvitationDetailsFormStep.vue
> +				store.updatePayload(
Updating invitation payload with the value it already has? Does it do anything? Or maybe could be removed?

2024-10-22 13:24 UTC, jardakotesovec commented on src/pages/userInvitation/UserInvitationEmailComposerStep.vue
> -		:recipient-options="props.email.recipientOptions"
Can't make comment above, as its not part of the PR. But we don't support attaching files in context sending invite, right? So the props like   attach-files-label, attachers, attachments, ...  can be removed.

2024-10-22 13:26 UTC, ipula commented on src/pages/userInvitation/UserInvitationEmailComposerStep.vue
> -		:recipient-options="props.email.recipientOptions"
I will remove those

2024-10-22 13:26 UTC, jardakotesovec commented on src/pages/userInvitation/UserInvitationEmailComposerStep.vue
> +
I think we don't need filter by validateFields anymore?

2024-10-22 13:33 UTC, ipula commented on src/pages/userInvitation/UserInvitationEmailComposerStep.vue
> +
I will check I used this most cases

2024-10-22 13:45 UTC, jardakotesovec commented on src/pages/acceptInvitation/AcceptInvitationPageStore.js
> +					'password',
I don't think that password is being passed from api.

2024-10-22 13:47 UTC, jardakotesovec commented on src/pages/acceptInvitation/AcceptInvitationPageStore.js
> +						if (Object.keys(updatedPayload.value).includes(field)) {
Do we still need to check the validateFields? If we are sending only the updated fields?

2024-10-22 13:48 UTC, jardakotesovec commented on src/pages/acceptInvitation/AcceptInvitationPageStore.js
> +					}
Can you give me please example when this would happen that updatedPayload would be null?

2024-10-22 13:50 UTC, jardakotesovec commented on src/pages/acceptInvitation/AcceptInvitationPageStore.js
> +			if (!acceptinvitationPayload.value.privacyStatement) {
please fix camelcase: acceptinvitationPayload -> acceptInvitationPayload

2024-10-22 13:53 UTC, ipula commented on src/pages/acceptInvitation/AcceptInvitationPageStore.js
> +						if (Object.keys(updatedPayload.value).includes(field)) {
But in the mockups familyname country etc.. are required therefor we need to add those somehow.

2024-10-22 13:56 UTC, jardakotesovec commented on src/pages/acceptInvitation/AcceptInvitationPageStore.js
> +									const {redirectToPage} = useUrl('submissions');
Just asked @defstat about what error scenario might happen on finalise - ideally it would be handled as well - and we would show error. Please follow-up with @defstat on some particular scenario that could be tested.

2024-10-22 14:00 UTC, jardakotesovec commented on src/pages/acceptInvitation/AcceptInvitationReview.vue
> +						<div
I think that you already iterate over the sections array in the AcceptInvitationPage? So maybe unnecessary to do it here again?

2024-10-22 14:03 UTC, ipula commented on src/pages/acceptInvitation/AcceptInvitationReview.vue
> +						<div
I use like `step.sections[0]`. Is it ok?

2024-10-22 14:10 UTC, ipula commented on src/pages/userInvitation/UserInvitationDetailsFormStep.vue
> +				store.updatePayload(
I updated this now. Please have look after the commit

2024-10-22 14:57 UTC, jardakotesovec commented on src/pages/acceptInvitation/AcceptInvitationReview.vue
> +								</div>
Locale and individual fields should not have same heading level. So lets move the fields to h5 for now.

2024-10-22 15:00 UTC, jardakotesovec commented on src/pages/acceptInvitation/AcceptInvitationReview.vue
> +									{{ t('common.edit') }}
Please move the heading and edit button outside of the loop, as its before the individual locales start. It will be than easier to replace eventually the loop with locales with FormDisplay or something.

2024-10-22 15:03 UTC, jardakotesovec commented on src/pages/acceptInvitation/AcceptInvitationReview.vue
> +									v-if="store.userId === null"
I added multilingual example for FormDisplay to storybook on main branch..   So that now supports multilingual form, but its not flexible enough yet to display some of the custom parts here.

But you should be able to use directly the FieldTextDisplay and FieldSelectDisplay,

FieldTextDisplay now supports displayLocale prop.

2024-10-22 15:04 UTC, ipula commented on src/pages/acceptInvitation/AcceptInvitationReview.vue
> +									v-if="store.userId === null"
I will use that

2024-10-22 15:06 UTC, jardakotesovec commented on src/pages/acceptInvitation/AcceptInvitationUserAccountDetails.vue
>  			t('acceptInvitation.privacyStatement.btn') +
a element should suffice, no need for additional button. If its link its better to just use the 'a' element if possible.

2024-10-22 15:19 UTC, jardakotesovec commented on src/pages/acceptInvitation/AcceptInvitationPageStore.js
> +						if (Object.keys(updatedPayload.value).includes(field)) {
Right.. I still have bit unclear understanding how exactly the updatedPayload works. 

I thought that your intention was to update updatedPayload when given section is displayed.. to ensure that all metadata are included there? In other words that you rely on the fact that everything on the page which is there either from the start or updated from user ends up in updatedPayload - and thats what you send to server.  

Therefore I am bit confused what validateFields are addressing here?

2024-10-22 15:40 UTC, jardakotesovec commented on src/pages/acceptInvitation/AcceptInvitationReview.vue
> +						<div
Is intention here just to find the form from the userDetails to reuse it?

If thats the case I would suggest just pass this form to both steps, so its available to both independently.

2024-10-24 17:19 UTC, merged