pkp/pkp-lib#9744 Migrate older Tables to newer Table API
pkp/ui-library pull request #389
Opened 2024-07-26 14:43 UTC by blesildaramirez

2024-08-07 11:48 UTC, jardakotesovec commented on src/components/Container/StatsPage.stories.js
> +								<TableCell>{{ row.total }}</TableCell>
I see that in previous code there was tooltip included also?

2024-08-07 11:57 UTC, jardakotesovec commented on src/components/Container/StatsPage.stories.js
> +						aria-label="Trends"
Also please check whether the column sizing works well.. As there seems to be some style overrides outside of the table. Again this is something we are trying to get rid off..   Instead of we are putting additional props and variants on components to be able handle different layout behaviour.

If you would conclude for example on this one that it requires some addition to the new Table, let me know. You can for example see that I already added couple of props to TableCell, like `noWrap` or `fullWidthTruncated` to handle some of the layout scenarios I had to deal with.
<img width="887" alt="Screenshot 2024-08-07 at 13 55 08" src="https://github.com/user-attachments/assets/b6198aa3-b482-4a55-a98a-f3de58f2c8b7">

2024-08-07 11:59 UTC, jardakotesovec commented on src/components/TableNext/TableCell.vue
>  		:class="classes"
Adding class from legacy table cell? If we need improve styling in new one - we would do it with tailwindcss..

2024-08-07 11:59 UTC, jardakotesovec commented on src/components/TableNext/TableRow.vue
> +	>
Same issue here.. not sure why it was exactly added?

2024-08-30 17:45 UTC, blesildaramirez commented on src/components/Container/StatsPage.stories.js
> +						aria-label="Trends"
Update here, I just added a class="!max-w-[8rem] truncate" directly on my use of TableColumn. It's not common to have long column names in the tables I migrated so I think this would be enough.

2024-09-03 13:39 UTC, jardakotesovec requested changes
Just couple small things.. its very close to being merged :-)

2024-09-03 13:39 UTC, jardakotesovec commented on src/pages/jobs/FailedJobsPage.vue
> +				<table-cell>{{ row.displayName }}</table-cell>
Its interesting that this has not been caught by eslint to be TableCell.

2024-09-03 13:39 UTC, jardakotesovec commented on src/pages/jobs/JobsPage.vue
> +};
I suspect that extending from 'JobsPage' from containers might get confusing - what about rename it to JobsPageBase and move that to pages/jobs ?

2024-09-04 15:36 UTC, jardakotesovec commented on src/components/Container/StatsPage.stories.js
> +						aria-label="Trends"
@blesildaramirez Can you check whether these additional classes are still necessary?

If so - I still would like to look into better options than such class overrides..

2024-09-04 15:39 UTC, jardakotesovec commented on src/pages/jobs/JobsPage.vue
> +};
Seems still not moved to pages/jobs?

2024-09-04 19:04 UTC, blesildaramirez commented on src/components/Container/StatsPage.stories.js
> +						aria-label="Trends"
Removing the added class somehow worked and doesn't overlap (like from your screenshot above). So best to remove the class override. Thanks!

2024-09-05 07:16 UTC, jardakotesovec approved these changes

2024-09-05 12:31 UTC, merged