Author Affiliations (work in progress)
pkp/ui-library pull request #417
Opened 2024-09-27 13:51 UTC by GaziYucel

2024-10-21 12:05 UTC, jardakotesovec commented on src/components/Form/fields/FieldAffiliations.stories.js
> +			const supportedLocales = args.supportedLocales;
Stories should not contain the logic from the component itself. Just imported and use it and pass props to it. 

Could can check out other Form fields for example.

2024-10-29 09:25 UTC, GaziYucel commented
I am waiting for a variant of the FieldBaseSuggest.vue component. After this, this PR can be wrapped up.

2024-11-20 13:08 UTC, GaziYucel commented
Hi @jardakotesovec,

I have implemented everything we discussed and all seems to work. 

There are some notes:
- you mentioned that Blessie was working on a variant of FieldBaseSuggest.vue which I can use;
- I have used <input type="text" for input fields. It would be better to have a very simple Vue component to use. This would have the following advantages:
  - less clutter and cleaner code
  - better accessibility
- error handling
  -  this is not implemented a la OJS
  - the check I do: there should be a ROR or at least one name and the name should be the primary locale
  - if this is not true, I disable the 'Add' button
  - saving the form is still enabled
- UI design
  - @Devika008 used a pie to show how many translations there are. I couldn't do this, because there is no component for this. I implemented "MultilingualProgress" instead
  - Devika placed the text/link "# of # translations completed" below the input fields. I moved this to above, because this makes the interface less jumpy

2025-01-10 16:43 UTC, GaziYucel commented
Hi @jardakotesovec,

I have implemented the new FieldRorAutosuggest (FieldAffiliationsRorAutoSuggest) component of @blesildaramirez. 

I think the PR is ready for review now. Thanks. 

@bozana: fyi

2025-01-13 12:36 UTC, GaziYucel commented
I am copying this from Mattermost to here, so it's on the list to check. 

As mentioned before, I think AbortController in src/composables/useFetch.js is not working as intended. Removing or adding async / await does not help. 

You can recreate this with the following two files, which are also in this PR. 

* src/components/Form/fields/FieldAffiliationsTest.stories.js
* src/components/Form/fields/FieldAffiliationsTest.vue

2025-02-04 12:45 UTC, jardakotesovec requested changes

2025-02-04 12:45 UTC, jardakotesovec commented on src/components/Form/fields/FieldAffiliations.vue
> +								</a>
Minor suggestion, just fyi, when passing some text constant to the props, you can just skip the colon and do `icon="ROR"` class="ml-1 h-6 w-6"

Instead of ml-1 probably ms-1 is better as that should work for RTL layout as well.

2025-02-04 12:45 UTC, jardakotesovec commented on src/components/Form/fields/FieldAffiliations.vue
> +											<div>
I think here the FieldText also should work well here. As there is lots being replicated from that component anyway.

2025-02-04 12:45 UTC, jardakotesovec commented on src/components/Form/fields/FieldAffiliations.vue
> +												/>
Here to avoid custom error logic - I would suggest just to indicate that its required and if someone deletes it maybe just disabling the add button would be obvious enough. But thats just my opinion, its probably good either way.

2025-02-04 12:45 UTC, jardakotesovec commented on src/components/Form/fields/FieldAffiliations.vue
> +									class="pkpButton border-transparent py-2 text-lg-semibold"
Any reason not to use our Button.vue component? Similarly like with the table wi intend to use our Button to ensure consistent rendering, rather than native component.

2025-02-04 12:45 UTC, jardakotesovec commented on src/components/Form/fields/FieldAffiliations.vue
> +	},
What scenario this should address? Its bit intricate to reason about this, as its changing currentValue when the currentValue got changed. I think only reason why its not infinite loop is because the makeCurrentValueCompatible is not updating the 'value', but inline fields.

Would like to have cleaner solution.

2025-02-04 12:45 UTC, jardakotesovec commented on src/components/Form/fields/FieldAffiliations.vue
> +					close();
I suspect that these in-object edits don't trigger the setter, which emits the change to the form. 

Better practice (chatgpt can provide more detailed  explanation) can be
```
  currentValue.value = currentValue.value.filter((_, i) => i !== index);

``

2025-02-04 12:45 UTC, jardakotesovec commented on src/components/Form/fields/FieldAffiliations.vue
> +function makeCurrentValueCompatible() {
Please add comment to explain what scenario is this function addressing.

2025-02-04 12:45 UTC, jardakotesovec commented on src/components/Form/fields/FieldAffiliations.vue
> +	position: relative;
I see that for most cases the tailwindcss is used, which is now preferred method. Can we also move these to the tailwindcss?

2025-02-04 12:45 UTC, jardakotesovec commented on src/components/Form/fields/FieldAffiliations.vue
> +const defaultLocale = 'en';
How this defaultLocale exactly works? I see its used
```
							<span class="text-lg-semibold">
								{{
									t('user.affiliations.searchPhraseLabel', {
										language: getLocaleDisplayName(defaultLocale),
									})
								}}
							</span>

```
Which suggest that if english is not primary language that it would not work? Can you check?

2025-02-04 13:06 UTC, GaziYucel commented on src/components/Form/fields/FieldAffiliations.vue
> +								</a>
icon="ROR" doesn't work, only :icon="ROR" works. You can quickly see this in storybook.

2025-02-04 13:19 UTC, GaziYucel commented on src/components/Form/fields/FieldAffiliations.vue
> +											<div>
The problem I had with FieldText is that the value is not binded two ways. I see that you replaced my "input" with FieldText in the affiliations loop. Look closely there, it is not working. The binding is only one way, thus showing but the object is not updated. That's what I meant that I couldn't make it work without changes in FieldText component.

2025-02-04 13:39 UTC, GaziYucel commented on src/components/Form/fields/FieldAffiliations.vue
> +	},
The main goal here is to get all locales correct when the affiliations comes from the database. So I think it would suffice to run this only once at onMounted. What do you think, would this then be okay for you?

2025-02-04 14:02 UTC, GaziYucel commented on src/components/Form/fields/FieldAffiliations.vue
> +const defaultLocale = 'en';
The label for the search phrase should state that the search phrase should be input in English. That's why I have 'en' as the locale there. This is how @Devika008 wanted this.

2025-02-04 16:45 UTC, GaziYucel commented on src/components/Form/fields/FieldAffiliations.vue
> +								</a>
Found why, notice the difference: `icon="ROR"` <> `:icon="'ROR'"`
Without the colon, the value should be ROR, not 'ROR'. Sorry.

2025-02-05 09:08 UTC, bozana commented on src/components/Form/fields/FieldAffiliations.vue
> +const defaultLocale = 'en';
I think this should be the submission primary locale -- it does not need to be English -- the journal could not have English at all.

2025-02-05 09:10 UTC, bozana commented on src/components/Form/fields/FieldAffiliations.vue
> +const defaultLocale = 'en';
And by the way: it seems the contributor form does not handle/display the submission primary locale correctly, s https://github.com/pkp/pkp-lib/issues/10879.

2025-02-05 11:23 UTC, GaziYucel commented on src/components/Form/fields/FieldAffiliations.vue
> +function makeCurrentValueCompatible() {
I removed this method completely. At onMounted(), the names are only sorted now with the primary first. 
Apparently, this is already done in the backend in the class Schema.

2025-02-05 11:23 UTC, GaziYucel commented on src/components/Form/fields/FieldAffiliations.vue
> +	},
This method is removed.

2025-02-05 12:29 UTC, jardakotesovec requested changes
Thank you for the updates. Could you please check couple more? Should be easy updates.

2025-02-05 12:29 UTC, jardakotesovec commented on src/components/ListPanel/contributors/ContributorsListPanel.vue
> +				}
Do we need to copy this from form to the field? By looking to FieldBase I see that it should be getting these two information as props - primaryLocale and locales.

2025-02-05 12:29 UTC, jardakotesovec commented on src/components/Form/fields/FieldAffiliations.vue
> +								@action="rowActionsHandler"
Instead of changing DropdownActions with additional property of `id`. Could you please just update it here:

(actionName) => rowActionsHandler(actionName, affiliationIndex)

2025-02-05 12:29 UTC, jardakotesovec commented on src/components/Form/fields/FieldAffiliations.vue
> +	if (typeof param === 'object' && param.length === 2) {
Could we just be explicit abyt the arguments here, like rowActionhandler(actionName, affiliationIndex)?

2025-02-05 12:47 UTC, GaziYucel commented on src/components/ListPanel/contributors/ContributorsListPanel.vue
> +				}
How would I get these from FieldBase in my component FieldAffiliations? Can you help me with this?

2025-02-05 13:26 UTC, jardakotesovec commented on src/components/ListPanel/contributors/ContributorsListPanel.vue
> +				}
This means that its being passed to all fields. Including your one. So if you just add it to the FieldAffiliation props - it should become available to you.

2025-02-05 16:16 UTC, jardakotesovec approved these changes
At some point we should do some screen reader accessibility testing. But don't have bandwidth for that at this point. 

I think its in good enough shape to be merged. Thank you for the hard work on this!

2025-02-06 14:00 UTC, merged