pkp/pkp-lib#9658 user access table and table actions
pkp/ui-library pull request #437
Opened 2024-10-28 17:13 UTC by ipula

2024-11-12 08:17 UTC, jardakotesovec commented
@withanage @ipula Whats missing is to determine which actions would be available to current user. Here is the logic from original table https://github.com/pkp/pkp-lib/blob/72087f4dabb1e80629b33639e3568501fd309fe2/controllers/grid/settings/user/UserGridRow.php#L84 

Most complex likely is LoginAs. For that I would ask Hafsa, whether she could introduce it to the /users endpoint as well, because she worked on the reviewers - https://github.com/pkp/pkp-lib/issues/10290

But meanwhile check whether the other checks (for other actions) would be easy to implement client side or whether there is also some additional complexity, where you don't have enough information client side and it would be necessary to calculate it server side.

2024-11-18 16:15 UTC, ipula commented
> @withanage @ipula Whats missing is to determine which actions would be available to current user. Here is the logic from original table https://github.com/pkp/pkp-lib/blob/72087f4dabb1e80629b33639e3568501fd309fe2/controllers/grid/settings/user/UserGridRow.php#L84
> 
> Most complex likely is LoginAs. For that I would ask Hafsa, whether she could introduce it to the /users endpoint as well, because she worked on the reviewers - [pkp/pkp-lib#10290](https://github.com/pkp/pkp-lib/issues/10290)
> 
> But meanwhile check whether the other checks (for other actions) would be easy to implement client side or whether there is also some additional complexity, where you don't have enough information client side and it would be necessary to calculate it server side.

We can check current user id matching with the userId in the actions in vuejs side and hide the actions that not allowed to by the same user.

2024-12-06 16:26 UTC, ipula commented
@jardakotesovec  I added the permission check on the loginAs and mergeUser based on https://github.com/pkp/pkp-lib/pull/10658. Please have a look

2025-01-27 12:44 UTC, jardakotesovec requested changes
This looks great! Basically very minor comments.

Only additional thing I would like to ask you to improve flexibility on extensibility.

Good example is the `getItemActions`, which will make possible to add some actions from plugin.

Using similar pattern and get list of columns from function so can we make possible to also add column from plugins?
Good example is here https://github.com/pkp/ui-library/blob/main/src/managers/GalleyManager/useGalleyManagerConfiguration.js#L59

2025-01-27 12:44 UTC, jardakotesovec commented on src/pages/userInvitation/UserInvitationDetailsFormStep.vue
> +				v-if="store.invitationPayload.phone"
Lets handle this in separate PR. There will be more metadata to add I think anyway.

2025-01-27 12:44 UTC, jardakotesovec commented on src/managers/UserAccessManager/UserAccessManagerStore.js
> +		function editUser(userObj) {
Its a detail, but as convention I always pass it as object, so there can be more data added later on. It happened me multiple times that there was more to add.  Could you adjust it so its  editUser({userObj})? Same for other action function as well.

2025-01-27 12:44 UTC, jardakotesovec commented on src/managers/UserAccessManager/UserAccessManagerStore.js
> +			window.location = sendInvitationPageUrl.value + '/' + userObj.id;
useUrl provides also redirectToPage, so we have same logic for redirects like this.

So something like this should work:
```
const {redirectToPage} = useUrl(`invitation/editUser/${userObj.id}`);
redirectToPage()
```

2025-01-27 12:44 UTC, jardakotesovec commented on src/managers/UserAccessManager/useUserAccessManagerActions.js
> +			if (closeData.dataChanged[0]) {
Seems unnecessary?

2025-02-04 18:43 UTC, merged